# Change character symbols
[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[âœ—](bold red)"

# Duration format
[cmd_duration]
format = "wasted time [$duration]($style)"
style = "bold purple"

# Directory
[directory]
repo_root_style = "bold blue"

# Memory
[memory_usage]
disabled = false
threshold = -1
format = "$symbol [$ram( | $swap)]($style) "
symbol = "ğŸ§ " 
style = "bold yellow"

# Username 
[username]
show_always = true
style_user = "bold blue"

# Time
[time]
format = "ğŸ•™ [$time]($style)\n"
time_format = "%R - %A %e %B"
style = "bold white"
disabled = false 
